// <auto-generated />
namespace ResolveGram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Email_Text : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_Text));
        
        string IMigrationMetadata.Id
        {
            get { return "201804070659586_Email_Text"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
